### ISSUE TITLE
Dockerfile for alpine?

### ISSUE THREAD

**Issue by murbanowicz** [nginxinc/docker-nginx-amplify#14]
Hi,
is it possible to build this image with nginx:alpine?
Would be nice if you could provide the Dockerfile to do that.

**Comment by steindaniel** [comment]
@murbanowicz Just out of curiosity, have you tested [this](https://raw.githubusercontent.com/nginxinc/nginx-amplify-agent/master/packages/install-source.sh) with Alpine 3.3 or above in Docker?

**Comment by iaejean** [comment]
@steindaniel I tried it, but I got a message for "missing file packages/requirements"

**Comment by steindaniel** [comment]
@iaejean It seems they've changed the version of Alpine to 3.7 (`os="alpine37"`) in the script.
I'll give it a go this week

**Comment by Starbix** [comment]
NGINX Amplify is included in my [dockerimage](https://github.com/Starbix/dockerimages/tree/master/nginx) if you guys want to check that out. Or you can build your own with the [fixed install script](https://github.com/Starbix/nginx-amplify-agent/blob/patch-2/packages/install-source.sh)

**Comment by gdzien** [comment]
Hello Marku,

I am Greg from NGINX Inc. I will be assisting you with this issue going forward.

Please allow me some time to explore feasibility of providing Alpine based Dockerfile for you. 
I should be able to provide further updates within 72 hours time. 

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/

**Comment by gdzien** [comment]
Hello again

Just a quick update to let you know that we are currently working on this, further updates will be provided next week.

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/

**Comment by gdzien** [comment]
Hello again,

In Alpine directory you can find Dockerfile (and required configs) that builds up alpine based docker image including nginx open source. Total weight of the image is 64.1MB after build.

I will now go ahead and close this issue.

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/
