### ISSUE TITLE
How do i set hostname at nginx docker-compose.yml

### ISSUE THREAD

**Issue by pabloaugusto** [nginxinc/docker-nginx-amplify#21]
Just did and not woking:

 amplify:
    image: nginx-amplify
    environment:
      API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      hostname: myhostname

**Comment by AltiUP** [comment]
For those who ask the same question : 
You must use the environment variable : AMPLIFY_IMAGENAME
