### ISSUE TITLE
is newer nginx version possible?

### ISSUE THREAD

**Issue by acurvers** [nginxinc/docker-nginx-amplify#28]
i see Nginx 1.13 is used, can newer / latest be used or is there a reason for 1.13?

thanks in advance!

**Comment by pavelsevcik** [comment]
To build image with new version of nginx you can just bump number in `Dockerfile` to version you want
- `FROM nginx:1.26.1`

Or you can 
- adopt `ARG` in `Dockerfile` as per [FIX: BASE_IMAGE as ARG](https://github.com/pavelsevcik/docker-nginx-amplify/commit/1b63800ffbec42e550f4375cec99d4a8132ac77e) 
- and then specify nginx version as argument in build command as 
  `docker build --build-arg BASE_IMAGE=nginx:1.26.1 .`

**Comment by f1dz** [comment]
@acurvers This issue should be close
