### ISSUE TITLE
Redundant command line parameter

### ISSUE THREAD

**Issue by arun-gupta** [nginxinc/docker-nginx-amplify#5]
Current instructions to run Amplify image are:

```
docker run --name mynginx1 -e API_KEY=ecfdee2e010899135c258d741a6effc7 -d nginx-amplify
```

After https://github.com/nginxinc/docker-nginx-amplify/issues/2 is fixed, then `-e API_KEY` may not be required since the key is specified in the `Dockerfile`.

**Comment by cdarwin** [comment]
Documentation and `Dockerfile` have been updated to recommend setting `API_KEY` at runtime rather than in the image. You could still set this in your own base image if you manage access to and trust your own registry, but we will not be doing so in our public builds.

Thanks!
