### ISSUE TITLE
Nginx access log file size

### ISSUE THREAD

**Issue by Cisneiros** [nginxinc/docker-nginx-amplify#8]
Hello! 

First of all, thank you for the image and documentation. I look forward to using Amplify on my Nginx Docker deployments.

I have a question regarding the Nginx log files. The README tells us to stop forwarding the log files and instead keep them in the container, so Amplify can parse the relevant data from them. My concern is that these logs may grow quite big and eventually fill up the entire disk.

Does the official Nginx image (or Amplify itself) automatically rotate these log files so they don't explode? If not, what steps would you recommend taking to deal with this?

Thank you!

**Comment by ptreyes** [comment]
Hi,

I believe you can safely use the "syslog" option here. Check the following sections of the Amplify docs:

https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#configuring-syslog

and

https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#using-syslog-for-metric-collection

You can configure additional logging and point it to the (agent's) syslog.

Hope this helps

**Comment by gdzien** [comment]
Hello Alexandre,

I am Greg from NGINX Inc. I will be assisting you with this issue going forward.

Please let us know if response provided by point-r solves your issue and we can mark this issue as closed?

If we will not receive response from you in over 7 days I will just go ahead and close this issue as completed.

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/

**Comment by Cisneiros** [comment]
This can be closed :)

**Comment by inyerade** [comment]
Hi @Cisneiros . What solution you apply? I have this problem I do not understand the solution
