### ISSUE TITLE
Pre built image

### ISSUE THREAD

**Issue by mikeymike** [nginxinc/docker-nginx-amplify#9]
Just wondering why there isn't a pre built image available to pull in through docker? As far as I can tell there nothing preventing this ?

**Comment by gdzien** [comment]
Hello there,

I am Greg from NGINX Inc. I will be assisting you with this issue going forward.
This is just to let you know that I am looking into this and should get back to you shortly.

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/

**Comment by gdzien** [comment]
Hello mikeymike,

Latest pre-built image can be found here by following this URL:
https://hub.docker.com/r/nginxinc/amplify-agent

I will be closing this issue now, please let us know if you need any further assistance.

Sincerely,
Grzegorz Dzien
DevOps Engineer
https://www.nginx.com/
